[default]
locale = "en-us"

[files]
extend-exclude = ["i18n-provider.md", "documentation/versioned_docs", "documentation/versioned_sidebars", "*.ts", "*.tsx"]

[default.extend-words]
nin = "nin"
OT = "OT"
prev = "prev"
prepend = "prepend"
prepended = "prepended"
goes = "goes"
IIF = "IIF"
Preact = "Preact"
AKS = "AKS"
ege = "ege"
nd = "nd"
DAA = "DAA"
bare = "bare"
