name: Check PR can be merged
on: [pull_request, pull_request_review, issue_comment]
jobs:
  automerge:
    if: ${{ 'pankod/refine' == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Helper
        id: runprhelper
        uses: Matticusau/pr-helper@v1.2.3
        with:
          repo-token: ${{ secrets.PANKOD_BOT_TOKEN }}
          enable-prmerge-automation: true
          enable-prcomment-automation: true
          enable-prlabel-automation: true
          prmerge-requireallchecks: true
          prmerge-requirereviewcount: 2
          prmerge-method: 'squash'
          prlabel-default: 'pr-onhold'
          prlabel-ready: 'pr-ready'
          prlabel-onhold: 'pr-onhold'
          prlabel-reviewrequired: 'review-required'
          prlabel-automerge: 'auto-merge'
          prmerge-deletebranch: true